### ISSUE TITLE
Missing manjaro-bluetooth metapackage

### ISSUE THREAD

**Issue by mbkma** [FreaxMATE/manjaro-iso-build#1]
Hi there!

Your image rocks!
Only one complaint so far: There is no bluetooth package installed. Hence, when I click the bluetooth settings button in the indicator panel, nothing happens.
Solution for me was to install the meta package `manjaro-bluetooth` with `blueman`.

Keep up the good work :+1:

**Comment by FreaxMATE** [comment]
Fixed with

https://github.com/FreaxMATE/iso-profiles/commit/216aecf6b6c09faf9eae2c93080aea3e7f7cc086
